#!/bin/sh

#config system
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci del system.led_wan
uci commit system

# config wireless
uci set wireless.radio0.cell_density='0'
uci set wireless.default_radio0.ssid='openwrt'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='12345678'
uci set wireless.radio1.cell_density='0'
uci set wireless.default_radio1.ssid='openwrt'
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key='12345678'
uci set wireless.default_radio1.macfilter='deny'
uci commit wireless
sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

#config network
uci set network.wan.proto="pppoe" 
uci set network.wan.username=""
uci set network.wan.password=""
uci commit network

uci set dropbear.@dropbear[0].Port=22
uci set dropbear.@dropbear[0].PasswordAuth=on
uci commit dropbear

exit 0
